# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: xÄ«ngkÅng
description: ''
keywords:
author: 
language: zh-CN
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: http://example.com
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: butterfly

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: ''


# # search (æœç´¢)
# # --------------------------------------

# # Algolia search
# algolia_search:
#   enable: true
#   hits:
#     per_page: 6

# # Local search
# local_search:
#   enable: true

# èœå•æ 
menu:
  é¦–é¡µ: / || fas fa-home
  æ—¶é—´è½´: /archives/ || fas fa-archive
  æ ‡ç±¤: /tags/ || fas fa-tags
  åˆ†ç±»: /categories/ || fas fa-folder-open
  æ¸…å•||fa fa-heartbeat:
    ç…§ç‰‡: /pic/ || fas fa-images
    ç”µå½±èµ„æº: /movies/ || fas fa-video
  ç•™è¨€: /guestbook
  å…³äº: /about/ || fas fa-heart

# ä¸»é¢˜
highlight_theme: mac light
# ä»£ç å¤åˆ¶åŠŸèƒ½
highlight_copy: true
# ç¤¾äº¤å›¾æ ‡
social:
  fab fa-github: https://github.com/start-point || Github
  fas fa-envelope: mailto:echo_c120@163.com || Email
# ä¸»é¡µé¡¶éƒ¨å›¾ç‰‡
index_img: /img/bg/bg4.jpg
# å­é¡µé¢é»˜è®¤é¡¶éƒ¨å›¾ç‰‡
category_img:  /img/bg/bg4.jpg
# å½’æ¡£é¡µé¢çš„
archive_img: /img/bg/bg4.jpg
# çš„æ ‡ç­¾é¡µé¢
tag_img:  /img/bg/bg4.jpg
# ç”¨äºæµè§ˆå™¨æ ‡ç­¾çš„å›¾æ ‡
# Icon for browser tab
favicon: /img/foc.png

post_meta:
  page:
    date_type: both # created or updated or both ä¸»é¡µæ–‡ç« æ—¥æœŸæ˜¯åˆ›å»ºæ—¥æˆ–è€…æ›´æ–°æ—¥æˆ–éƒ½æ˜¾ç¤º
    date_format: relative # date/relative æ˜¾ç¤ºæ—¥æœŸè¿˜æ˜¯ç›¸å¯¹æ—¥æœŸ
    categories: true # true or false ä¸»é¡µæ˜¯å¦æ˜¾ç¤ºåˆ†ç±»
    tags: true # true or false ä¸»é¡µæ˜¯å¦æ˜¾ç¤ºæ ‡ç±¤
    label: true # true or false æ˜¾ç¤ºæè¿°æ€§æ–‡å­—
  post:
    date_type: both # created or updated or both æ–‡ç« é¡µæ—¥æœŸæ˜¯åˆ›å»ºæ—¥æˆ–è€…æ›´æ–°æ—¥æˆ–éƒ½æ˜¾ç¤º
    date_format: relative # date/relative æ˜¾ç¤ºæ—¥æœŸè¿˜æ˜¯ç›¸å¯¹æ—¥æœŸ
    categories: true # true or false æ–‡ç« é¡µæ˜¯å¦æ˜¾ç¤ºåˆ†ç±»
    tags: true # true or false æ–‡ç« é¡µæ˜¯å¦æ˜¾ç¤ºæ ‡ç±¤
    label: true # true or false æ˜¾ç¤ºæè¿°æ€§æ–‡å­—

copyright: false

# åœ¨æ–‡ç« é¡µï¼Œä¼šæœ‰ä¸€ä¸ªç›®å½•ï¼Œç”¨äºæ˜¾ç¤ºTOCã€‚
toc:
  enable: true
  number: true
  style_simple: true

# å¤´åƒ
avatar:
  img: /img/t.png
  effect: false # å¤´åƒä¼šä¸€ç›´è½¬åœˆ
  photofigcaption: true

footer:
  owner:
    enable: true
    since: <a href="https://beian.miit.gov.cn/">çš–ICPå¤‡2021014023å·</a>
    custom_text: /index.html

# è®¿é—®äººæ•°
busuanzi:
  site_uv: true
  site_pv: true
  page_pv: true

# Background effects (èƒŒæ™¯ç‰¹æ•ˆ)
# --------------------------------------

# canvas_ribbon (éœæ­¢å½©å¸¶èƒŒæ™¯)
# See: https://github.com/hustcc/ribbon.js
canvas_ribbon:
  enable: false
  size: 150
  alpha: 0.6
  zIndex: -1
  click_to_change: false
  mobile: false

# Fluttering Ribbon (å‹•æ…‹å½©å¸¶)
canvas_fluttering_ribbon:
  enable: false
  mobile: false

# canvas_nest
# https://github.com/hustcc/canvas-nest.js
canvas_nest:
  enable: true
  color: '0,0,255' #color of lines, default: '0,0,0'; RGB values: (R,G,B).(note: use ',' to separate.)
  opacity: 0.7 # the opacity of line (0~1), default: 0.5.
  zIndex: -1 # z-index property of the background, default: -1.
  count: 99 # the number of lines, default: 99.
  mobile: true

# Typewriter Effect (æ‰“å­—æ•ˆæœ)
# https://github.com/disjukr/activate-power-mode
activate_power_mode:
  enable: true
  colorful: true # open particle animation (å†’å…‰ç‰¹æ•ˆ)
  shake: false #  open shake (æŠ–å‹•ç‰¹æ•ˆ)
  mobile: true

# Mouse click effects: fireworks (é¼ æ¨™é»æ“Šæ•ˆæœ: ç…™ç«ç‰¹æ•ˆ)
fireworks:
  enable: false
  zIndex: 9999 # -1 or 9999
  mobile: false

# Mouse click effects: Heart symbol (é¼ æ¨™é»æ“Šæ•ˆæœ: æ„›å¿ƒ)
click_heart:
  enable: true
  mobile: true

# Mouse click effects: words (é¼ æ¨™é»æ“Šæ•ˆæœ: æ–‡å­—)
ClickShowText:
  enable: false
  text:
    - é™ˆ
    - æ°¸
    - é¾™
    - çš„
    - æ˜Ÿ
    - ç©º
  fontSize: 15px
  random: false
  mobile: false

# Default display mode (ç¶²ç«™é»˜èªçš„é¡¯ç¤ºæ¨¡å¼)
# light (default) / dark
display_mode: light

# Beautify (ç¾åŒ–é é¢é¡¯ç¤º)
# ç¾åŒ–é¡µé¢æ˜¾ç¤º
beautify:
  enable: true
  field: site # site/post
  title-prefix-icon: '\f0c1'
  title-prefix-icon-color: "#F47466"
# Beautify/Effect (ç¾åŒ–/æ•ˆæœ)
# --------------------------------------

# Theme color for customize
# Notice: color value must in double quotes like "#000" or may cause error!

theme_color:
  enable: true
  main: "#49B1F5"
  paginator: "#00c4b6"
  button_hover: "#FF7242"
  text_selection: "#00c4b6"
  link_color: "#99a9bf"
  meta_color: "#858585"
  hr_color: "#A4D8FA"
  code_foreground: "#F47466"
  code_background: "rgba(27, 31, 35, .05)"
  toc_color: "#00c4b6"
  blockquote_padding_color: "#49b1f5"
  blockquote_background_color: "#49b1f5"

# The top_img settings of home page
# default: top img - full screen, site info - middle (é»˜èªtop_imgå…¨å±ï¼Œsite_infoåœ¨ä¸­é–“)
# The position of site info, eg: 300px/300em/300rem/10% (ä¸»é æ¨™é¡Œè·é›¢é ‚éƒ¨è·é›¢)
index_site_info_top:
# The height of top_img, eg: 300px/300em/300rem (ä¸»é top_imgé«˜åº¦)
index_top_img_height:

# The user interface setting of category and tag page (categoryå’Œtagé çš„UIè¨­ç½®)
# index - same as Homepage UI (index å€¼ä»£è¡¨ UIå°‡èˆ‡é¦–é çš„UIä¸€æ¨£)
# default - same as archives UI é»˜èªè·Ÿarchivesé é¢UIä¸€æ¨£
category_ui: # ç•™ç©ºæˆ– index
tag_ui: # ç•™ç©ºæˆ– index

# Website Background (è¨­ç½®ç¶²ç«™èƒŒæ™¯)
# can set it to color or image (å¯è¨­ç½®åœ–ç‰‡ æˆ–è€… é¡”è‰²)
# The formal of image: url(http://xxxxxx.com/xxx.jpg)
background: 

# Footer Background
footer_bg: /img/bg/bg4.jpg

# the position of bottom right button/default unit: px (å³ä¸‹è§’æŒ‰éˆ•è·é›¢åº•éƒ¨çš„è·é›¢/é»˜èªå–®ä½ç‚ºpx)
rightside-bottom:

# Enter transitions (é–‹å•“ç¶²é é€²å…¥æ•ˆæœ)
enter_transitions: true

  
aside:
  enable: true
  hide: false
  button: true
  mobile: true # display on mobile
  position: right # left or right
  card_author:
    enable: true
    description:
    button:
      enable: true
      icon: fab fa-github
      text: xÄ«ngkÅng sky
      link: https://github.com/start-point
  card_announcement:
    enable: true
    content: <a href="https://blog.csdn.net/Eternalyii">csdnåšå®¢é“¾æ¥</a>
  card_recent_post:
    enable: true
    limit: 5 # if set 0 will show all
    sort: date # date or updated
    sort_order: # Don't modify the setting unless you know how it works
  card_categories:
    enable: true
    limit: 8 # if set 0 will show all
    expand: none # none/true/false
    sort_order: # Don't modify the setting unless you know how it works
  card_tags:
    enable: true
    limit: 40 # if set 0 will show all
    color: false
    sort_order: # Don't modify the setting unless you know how it works
  card_archives:
    enable: true
    type: monthly # yearly or monthly
    format: MMMM YYYY # eg: YYYYå¹´MMæœˆ
    order: -1 # Sort of order. 1, asc for ascending; -1, desc for descending
    limit: 8 # if set 0 will show all
    sort_order: # Don't modify the setting unless you know how it works
  card_webinfo:
    enable: true
    post_count: true
    last_push_date: true
    sort_order: # Don't modify the setting unless you know how it works
  

# Global font settings
# Don't modify the following settings unless you know how they work (éå¿…è¦ä¸è¦ä¿®æ”¹)
font:
  global-font-size:
  code-font-size:
  font-family:
  code-font-family:

# Font settings for the site title and site subtitle
# å·¦ä¸Šè§’ç¶²ç«™åå­— ä¸»é å±…ä¸­ç¶²ç«™åå­—
blog_title_font: 
  font_link: 
  font-family: 

# The setting of divider icon (æ°´å¹³åˆ†éš”ç·šåœ–æ¨™è¨­ç½®)
hr_icon:
  enable: true
  icon: # the unicode value of Font Awesome icon, such as '\3423'
  icon-top:

# Font settings for the site title and site subtitle
# å·¦ä¸Šè§’ç½‘ç«™åå­— ä¸»é¡µå±…ä¸­ç½‘ç«™åå­—
log_title_font:
  font_link:
  font-family: Titillium Web, 'PingFang SC', 'Hiragino Sans GB', 'Microsoft JhengHei', 'Microsoft YaHei', sans-serif


# ä¸»é¡µsubtitle
subtitle:
  enable: true
  # æ‰“å­—æ•ˆæœ
  effect: true
  # å¾ªç¯æˆ–è€…åªæ‰“å­—ä¸€æ¬¡
  loop: true
  # sourceè°ƒç”¨ç¬¬ä¸‰æ–¹æœåŠ¡
  # source: false å…³é—­è°ƒç”¨
  # source: 1  è°ƒç”¨æå¤©apiçš„éšæœºè¯­å½•ï¼ˆç®€ä½“ï¼‰ 
  # source: 2  è°ƒç”¨ä¸€è¨€ç½‘çš„ä¸€å¥è¯ï¼ˆç®€ä½“ï¼‰ 
  # source: 3  è°ƒç”¨ä¸€å¥ç½‘ï¼ˆç®€ä½“ï¼‰ 
  # source: 4  è°ƒç”¨ä»Šæ—¥è¯—è¯ï¼ˆç®€ä½“
  # subtitle ä¼šå…ˆæ˜¾ç¤º source , å†æ˜¾ç¤º sub çš„å†…å®¹
  source: false
  # å¦‚æœæœ‰è‹±æ–‡é€—å·' , ',è¯·ä½¿ç”¨è½¬ä¹‰å­—å…ƒ &#44;
  # å¦‚æœæœ‰è‹±æ–‡åŒå¼•å·' " ',è¯·ä½¿ç”¨è½¬ä¹‰å­—å…ƒ &quot;
  # å¼€å¤´ä¸å…è®¸è½¬ä¹‰å­—å…ƒï¼Œå¦‚éœ€è¦ï¼Œè¯·æŠŠæ•´ä¸ªå¥å­ç”¨åŒå¼•å·åŒ…ä½
  # ä¾‹å¦‚ â€&quotNever put off till tomorrow what you can do today&quot"
  # å¦‚æœå…³é—­æ‰“å­—æ•ˆæœï¼Œsubtitleåªä¼šæ˜¾ç¤ºsubçš„ç¬¬ä¸€è¡Œæ–‡å­—
  sub:
    - MiÃ nxiÃ ng xÄ«ngkÅng biÄnchÃ©ngğŸ‰...
    - æˆ‘å¯¹æœˆäº®è®¸æ„¿ï¼Œæœ›å¤©ç©ºçš„æ˜Ÿæ˜Ÿè¶Šæ¥è¶Šå¤šğŸ‰... 
    - æœ›ä½ ç¦»æˆ‘è¶Šæ¥è¶Šè¿‘ğŸ‰...
    - æœ›å†™çš„bug ä¹Ÿè¶Šæ¥è¶Šå°‘ğŸ‰...
    
# Loading Animation (åŠ è¼‰å‹•ç•«)
preloader: true

# è¯„è®º
comments:
  # Up to two comments system, the first will be shown as default
  # Choose: Disqus/Disqusjs/Livere/Gitalk/Valine/Waline/Utterances/Facebook Comments/Twikoo
  use:
    - Valine
  text: true # Display the comment name next to the button
  # lazyload: The comment system will be load when comment element enters the browser's viewport.
  # If you set it to true, the comment count will be invalid
  lazyload: true
  count: true # Display comment count in top_img
  card_post_count: false # Display comment count in Home Page

# # è¯„è®º
valine:
  appId: QvznJaEE4SULOqPKkrH3AnKg-gzGzoHsz  # leancloud application app id
  appKey: owk9jlREHcMVpj328hqQ3Duv  # leancloud application app key
  pageSize: 10 # comment list page size
  avatar: monsterid # gravatar style https://valine.js.org/#/avatar
  lang: en # i18n: zh-CN/zh-TW/en/ja
  placeholder: è¨˜å¾—ç•™ä¸‹ä½ çš„æš±ç¨±å’Œéƒµç®±....å¯ä»¥å¿«é€Ÿæ”¶åˆ°å›å¾© # valine comment input placeholder(like: Please leave your footprints )
  guest_info: nick,mail,link #valine comment header info (nick/mail/link)
  recordIP: false # Record reviewer IP
  serverURLs: # This configuration is suitable for domestic custom domain name users, overseas version will be automatically detected (no need to manually fill in)
  bg: /img/comment_bg.png # valine background
  emojiCDN: # emoji CDN
  enableQQ: false # enable the Nickname box to automatically get QQ Nickname and QQ Avatar
  requiredFields: nick,mail # required fields (nick/mail)
  visitor: false
  option:

# æœç´¢
# search:
#   path: search.xml
#   field: post
#   content: true
#   template: ./search.xml
# local_search:
#   enable: true

# æ–‡ç« åº•éƒ¨ç‰ˆæƒå£°æ˜å…³é—­
post_copyright:
  copyright: false
  enable: false
  decode: false

# PWA
# See https://github.com/JLHwung/hexo-offline
# ---------------
# pwa:
#   enable: false
#   manifest: /pwa/manifest.json
#   apple_touch_icon: /pwa/apple-touch-icon.png
#   favicon_32_32: /pwa/32.png
#   favicon_16_16: /pwa/16.png
#   mask_icon: /pwa/safari-pinned-tab.svg

# Open graph meta tags
# https://developers.facebook.com/docs/sharing/webmasters/
Open_Graph_meta: true

# Add the vendor prefixes to ensure compatibility
css_prefix: true

# Inject
# Insert the code to head (before '</head>' tag) and the bottom (before '</body>' tag)
# æ’å…¥ä»£ç åˆ°å¤´éƒ¨ </head> ä¹‹å‰ å’Œ åº•éƒ¨ </body> ä¹‹å‰
inject:
  head:
    # - <link rel="stylesheet" href="/xxx.css">
  bottom:
    # - <script src="xxxx"></script>

# CDN
# Don't modify the following settings unless you know how they work
# éå¿…è¦è«‹ä¸è¦ä¿®æ”¹
CDN:
  # main
  main_css: /css/index.css
  jquery: https://cdn.jsdelivr.net/npm/jquery@latest/dist/jquery.min.js
  main: /js/main.js
  utils: /js/utils.js

  # pjax
  pjax: https://cdn.jsdelivr.net/npm/pjax/pjax.min.js

  # comments
  gitalk: https://cdn.jsdelivr.net/npm/gitalk@latest/dist/gitalk.min.js
  gitalk_css: https://cdn.jsdelivr.net/npm/gitalk/dist/gitalk.min.css
  valine: https://cdn.jsdelivr.net/npm/valine/dist/Valine.min.js
  disqusjs: https://cdn.jsdelivr.net/npm/disqusjs@1/dist/disqus.js
  disqusjs_css: https://cdn.jsdelivr.net/npm/disqusjs@1/dist/disqusjs.css
  utterances: https://utteranc.es/client.js
  twikoo: https://cdn.jsdelivr.net/npm/twikoo/dist/twikoo.all.min.js
  waline: https://cdn.jsdelivr.net/npm/@waline/client/dist/Waline.min.js

  # share
  addtoany: https://static.addtoany.com/menu/page.js
  sharejs: https://cdn.jsdelivr.net/npm/social-share.js/dist/js/social-share.min.js
  sharejs_css: https://cdn.jsdelivr.net/npm/social-share.js/dist/css/share.min.css

  # search
  local_search: /js/search/local-search.js
  algolia_js: /js/search/algolia.js
  algolia_search: https://cdn.jsdelivr.net/npm/instantsearch.js@2.10.5/dist/instantsearch.min.js
  algolia_search_css: https://cdn.jsdelivr.net/npm/instantsearch.js@2.10.5/dist/instantsearch.min.css

  # math
  mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  katex: https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css
  katex_copytex: https://cdn.jsdelivr.net/npm/katex@latest/dist/contrib/copy-tex.min.js
  katex_copytex_css: https://cdn.jsdelivr.net/npm/katex@latest/dist/contrib/copy-tex.css
  mermaid: https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js

  # count
  busuanzi: //busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js

  # background effect
  canvas_ribbon: https://cdn.jsdelivr.net/npm/butterfly-extsrc@1/dist/canvas-ribbon.min.js
  canvas_fluttering_ribbon: https://cdn.jsdelivr.net/npm/butterfly-extsrc@1/dist/canvas-fluttering-ribbon.min.js
  canvas_nest: https://cdn.jsdelivr.net/npm/butterfly-extsrc@1/dist/canvas-nest.min.js

  lazyload: https://cdn.jsdelivr.net/npm/vanilla-lazyload/dist/lazyload.iife.min.js
  instantpage: https://cdn.jsdelivr.net/npm/instant.page/instantpage.min.js
  typed: https://cdn.jsdelivr.net/npm/typed.js/lib/typed.min.js
  pangu: https://cdn.jsdelivr.net/npm/pangu/dist/browser/pangu.min.js

  # photo
  fancybox_css: https://cdn.jsdelivr.net/npm/@fancyapps/ui/dist/fancybox.css
  fancybox: https://cdn.jsdelivr.net/npm/@fancyapps/ui/dist/fancybox.umd.js
  medium_zoom: https://cdn.jsdelivr.net/npm/medium-zoom/dist/medium-zoom.min.js

  # snackbar
  snackbar_css: https://cdn.jsdelivr.net/npm/node-snackbar/dist/snackbar.min.css
  snackbar: https://cdn.jsdelivr.net/npm/node-snackbar/dist/snackbar.min.js

  # effect
  activate_power_mode: https://cdn.jsdelivr.net/npm/butterfly-extsrc@1/dist/activate-power-mode.min.js
  fireworks: https://cdn.jsdelivr.net/npm/butterfly-extsrc@1/dist/fireworks.min.js
  click_heart: https://cdn.jsdelivr.net/npm/butterfly-extsrc@1/dist/click-heart.min.js
  ClickShowText: https://cdn.jsdelivr.net/npm/butterfly-extsrc@1/dist/click-show-text.min.js

  # fontawesome
  fontawesome: https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free/css/all.min.css

  # Conversion between Traditional and Simplified Chinese
  translate: /js/tw_cn.js

  # justifiedGallery
  justifiedGallery_js: https://cdn.jsdelivr.net/npm/justifiedGallery/dist/js/jquery.justifiedGallery.min.js
  justifiedGallery_css: https://cdn.jsdelivr.net/npm/justifiedGallery/dist/css/justifiedGallery.min.css

  # aplayer
  aplayer_css: https://cdn.jsdelivr.net/npm/aplayer/dist/APlayer.min.css
  aplayer_js: https://cdn.jsdelivr.net/npm/aplayer/dist/APlayer.min.js
  meting_js: https://cdn.jsdelivr.net/gh/metowolf/MetingJS@1.2/dist/Meting.min.js

  # Prism.js
  prismjs_js: https://cdn.jsdelivr.net/npm/prismjs/prism.min.js
  prismjs_lineNumber_js: https://cdn.jsdelivr.net/npm/prismjs/plugins/line-numbers/prism-line-numbers.min.js
  prismjs_autoloader: https://cdn.jsdelivr.net/npm/prismjs/plugins/autoloader/prism-autoloader.min.js
