# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: ChenYongLong'Sky
subtitle: ''
description: ''
keywords:
author: ChenYongLong'Sky
language: zh-CN
timezone: ''

# ç”¨äºæµè§ˆå™¨æ ‡ç­¾çš„å›¾æ ‡
# Icon for browser tab
favicon: /img/foc.png

# ç”¨äºè‹¹æœè®¾å¤‡çš„å›¾æ ‡
# Icon for Apple touch
apple_touch_icon: /img/foc.png

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: http://example.com
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: fluid

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: ''

# ä¿®æ”¹åšå®¢é¡¶éƒ¨å³ä¾§çš„æ ‡é¢˜
navbar:
  blog_title: ChenYongLong'Sky

footer:
  statistics:
    enable: true
    source: "leancloud"  # å¯é€‰ leancloud | busuanzi  æ ¹æ®è‡ªå·±éœ€æ±‚é€‰æ‹©
    pv_format: "æ€»è®¿é—®é‡ {} æ¬¡"  # æ˜¾ç¤ºçš„æ–‡æœ¬ï¼Œ{}æ˜¯æ•°å­—çš„å ä½ç¬¦ï¼ˆå¿…é¡»åŒ…å«)ï¼Œä¸‹åŒ
    uv_format: "æ€»è®¿å®¢æ•° {} äºº"

post:
  math:
    enable: true
    specific: true
    engine: mathjax
  meta:
    author:  # ä½œè€…ï¼Œä¼˜å…ˆæ ¹æ® front-matter é‡Œ author å­—æ®µï¼Œå…¶æ¬¡æ˜¯ hexo é…ç½®ä¸­ author å€¼
      enable: true
    date:  # æ–‡ç« æ—¥æœŸï¼Œä¼˜å…ˆæ ¹æ® front-matter é‡Œ date å­—æ®µï¼Œå…¶æ¬¡æ˜¯ md æ–‡ä»¶æ—¥æœŸ
      enable: true
      format: "dddd, MMMM Do YYYY, h:mm a"  # æ ¼å¼å‚ç…§ ISO-8601 æ—¥æœŸæ ¼å¼åŒ–
    wordcount:  # å­—æ•°ç»Ÿè®¡
      enable: true
      format: "{} å­—"  # æ˜¾ç¤ºçš„æ–‡æœ¬ï¼Œ{}æ˜¯æ•°å­—çš„å ä½ç¬¦ï¼ˆå¿…é¡»åŒ…å«)ï¼Œä¸‹åŒ
    min2read:  # é˜…è¯»æ—¶é—´
      enable: true
      format: "{} åˆ†é’Ÿ"
    views:  # é˜…è¯»æ¬¡æ•°
      enable: true
      source: "busuanzi"  # ç»Ÿè®¡æ•°æ®æ¥æºï¼Œå¯é€‰ï¼šleancloud | busuanzi   æ³¨æ„ä¸è’œå­ä¼šé—´æ­‡æŠ½é£
      format: "{} æ¬¡"


web_analytics:  # ç½‘é¡µè®¿é—®ç»Ÿè®¡
  enable: true # é»˜è®¤ä¸ºfalseï¼Œå¯ç”¨ç½‘é¡µç»Ÿè®¡æ”¹ä¸ºtrueå³å¯
  baidu:  # ç™¾åº¦ç»Ÿè®¡çš„Keyï¼Œå‚è§ https://tongji.baidu.com/sc-web/10000033910/home/site/getjs?siteId=13751376 ä»£ç è·å–ä¸­ hm.js? åè¾¹çš„å­—ç¬¦ä¸²
  google:  # Googleç»Ÿè®¡çš„Tracking IDï¼Œå‚è§ https://analytics.google.com/analytics/web/
  tencent:  # è…¾è®¯ç»Ÿè®¡çš„H5 App idï¼Œå‚è§ https://mta.qq.com/h5/manage/ctr_app_manage (å¼€å¯é«˜çº§åŠŸèƒ½æ‰æœ‰cid)
    sid:
    cid:
  woyaola:  # 51.laç«™ç‚¹ç»Ÿè®¡IDï¼Œå‚è§ https://www.51.la/user/site/index
  cnzz:  # å‹ç›Ÿ/cnzzç«™ç‚¹ç»Ÿè®¡web_idï¼Œå‚è§ https://web.umeng.com/main.php?c=site&a=show
  leancloud:  # LeanCloud è®¡æ•°ç»Ÿè®¡ï¼Œå¯ç”¨äº PV UV å±•ç¤ºï¼Œå¦‚æœ web_analytics.enable æ²¡æœ‰å¼€å¯ï¼ŒPV UV å±•ç¤ºåªä¼šæŸ¥è¯¢ï¼Œä¸ä¼šå¢åŠ 
    app_id:
    app_key:
    server_url:  # REST API æœåŠ¡å™¨åœ°å€ï¼Œå›½é™…ç‰ˆä¸å¡«


code:
  copy_btn: true
  highlight:
    enable: true
    line_number: true
    lib: "highlightjs"
    highlightjs:
      style: 'Github Gist'
      bg_color: false
    prismjs:
      style: "default"
      preprocess: true

index:
  banner_img: /img/bg/bg4.jpg
  slogan:
    enable: true
    text: "MiÃ nxiÃ ng xÄ«ngkÅng biÄnchÃ©ngğŸ‰..."
    api:
      enable: false
      url: "https://v1.hitokoto.cn/"
      method: "GET"
      headers: {}
      keys: ["hitokoto"]

# # å¼€å¯è¯„è®ºæ¨¡å—
# post:
#   comments:
#     enable: true
#     type: utterances

# utterances:
#   repo:start-point/Create-repository
#   issue-term:pathname
#   label:#
#   theme:github-light
#   crossorigin:anonymous


#---------------------------
# åˆ†ç±»é¡µ
# Category Page
#---------------------------
category:
  enable: true
  banner_img: /img/bg/bg.jpg
  banner_img_height: 60
  banner_mask_alpha: 0.3

#---------------------------
# æ ‡ç­¾é¡µ
# Tag Page
#---------------------------
tag:
  enable: true
  banner_img: /img/bg/bg.jpg
  banner_img_height: 80
  banner_mask_alpha: 0.3
  subtitle:
  tagcloud:
    min_font: 15
    max_font: 30
    unit: px  # å­—å·å•ä½
    start_color: "#BBBBEE"
    end_color: "#337ab7"



#---------------------------
# å½’æ¡£é¡µ
# Archive Page
#---------------------------
archive:
  banner_img: /img/bg/bg.jpg
  banner_img_height: 60
  banner_mask_alpha: 0.3


# å…³äºé¡µçš„é…ç½®
about:
  enable: true
  banner_img: /img/bg/bg.jpg
  banner_img_height: 60
  banner_mask_alpha: 0.3
  avatar: /img/t.png
  name: "é™ˆæ°¸é¾™"
  intro: "ä¸€æ¯å’–å•¡â˜• ä¸€è¡Œä»£ç (âŠ™oâŠ™)ï¼Ÿ ä¸€ä¸ªBUG ç…ä¸€å¤©"
  icons: 
  #   class: 'iconfont icon-github-fill', link: 'https://github.com/start-point', tip: 'GitHub'
    - { class: 'iconfont icon-github-fill', link: 'https://github.com/start-point', tip: 'GitHub' }
    - { class: "iconfont icon-weibo-fill", link: "https://weibo.com/u/6570810703", tip: "å¾®åš" }
    - { class: "iconfont icon-wechat-fill", qrcode: "/img/we.png" }
